name: BuildAndPushDocker
on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get Git Version
      uses: docker://gittools/gitversion:5.5.1-linux-alpine.3.10-x64-netcoreapp3.1
      with:
        args: /github/workspace
      # /nofetch /exec /bin/sh /execargs "-c \"echo $GitVersion_FullSemVer > /github/workspace/version.txt\""
    - name: chech GV
      run: gitversion
    - name: print version
      run: cat ./version.txt
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: isieiam/se_ui
        tags: "2.0"
